mysociety/yournextrepresentative

- README.md
- candidates/static/candidates/_people.scss
- candidates/templates/candidates/_person_in_list.html
- candidates/tests/test_constituency_view.py
Fixes #124.
Makes candidate parties a bit easier to parse – especially for UKIP candidates who already have brackets in the party name.
> Remove brackets around candidate party on constituency page

- candidates/migrations/0004_auto__add_personredirect.py
- candidates/models.py
- candidates/popit.py
- candidates/templates/candidates/person-edit.html
- candidates/templates/candidates/person-versions.html
- candidates/tests/test_merge_people.py
- candidates/urls.py
- candidates/views.py
We're making this superuser only, since it's not trivial to revert a
merge in the same way that reverting a change to a field of a person
is.
When you go to a particular person's edit page, that person is
considered the 'primary' person, and the ID that you put into the
edit box is the 'secondary' person. In the case of any conflict
between the data, the field for the primary person is used.
The versions array of the primary person is prepended to the versions
array for the second person, and before them a "merged" version is
prepended. This isn't ideal - really, now that we support merging
you'd want a directed-acyclic graph of versions (like git, say) but I'm
reluctant to reinvent git's data model in a PopIt field.  As it is,
this might be confusing because the order of the versions is …
> Add a (superuser only) option to merge two people

- .gitignore
- candidates/management/commands/candidates_import_ppcs.py
- candidates/management/commands/candidates_update_popit_parties_from_ec_data.py
- candidates/management/commands/images.py
There have been some small changes which required updates:
* We're now loading the JSON from a URL rather than a submodule
* The de-registration dates are now in a separate field rather than
being appended to the party name
* The format of errors seems to have changed (see
https://github.com/mysociety/popit-api/issues/113 )
* Emblem images have to be fetched from
http://openelectoralcommission.org.uk/party_images/ rather than found
in the submodule.
> Update the EC importer to use openelectoralcommission.org.uk data

- .gitmodules
- README.md
- candidates/diffs.py
- candidates/management/commands/candidates_add_parlparse_id.py
- candidates/tests/test_version_diffs.py
- candidates/update.py
- conf/packages
- requirements.txt
Iterate over all the MPs from the 2010 election and add their parlparse/publicwhip id as an identifier. This should make it easier to do #144.
Fixes #143
> Add parlparse id to 2010 mps

- candidates/forms.py
It's common for people to enter Twitter usernames with a leading '@'
sign, and rejecting this just annoys people - if there's a leading '@',
strip it off and then check that the username only contains valid
characters.
> Strip off any leading @ in Twitter username in validation

- candidates/static/candidates/_finder.scss
The recent merge of the [profile page redesign](https://github.com/mysociety/yournextmp-popit/commit/46d2151eb7d66c7087f8114e0d751255da9ae10c) included the removal of the `.content__inner` div from the base template. The current homepage design expects `.content__inner` to be there, with 2em padding-top. Without it, the homepage form sits too low, and the fake shadows on either side don’t line up.
This would have been fixed by the new homepage layout in #154 but that hasn’t been merged yet. So here’s an interim fix.
Before:
After:
> Fix spacing above finder form on homepage

- cached_counts/management/commands/cached_counts_create.py
- cached_counts/templates/reports.html
- cached_counts/views.py
The statistics on the 'Numbers' page didn't obviously add up (see #185)
and the code that calculated them was a bit difficult to follow if you
wanted to work out why.  This commit hopefully makes their calculation
a bit clearer and also adds statistics to show the breakdown between
candidates who are standing again for the same party or a different party.
> Add standing again for the same / different party statistics

- candidates/templates/candidates/finder.html
The new homepage is excellent, and is very much worded for people who
want the data in bulk (“Don’t pay for a candidate database…”). So I
think we should perhaps link to the API / csv download page more
prominently.
> Add a more prominent link to the API page

- candidates/middleware.py
- candidates/templates/candidates/popit_down.html
- candidates/tests/test_popit_down_middleware.py
- mysite/settings.py
If PopIt is being restarted, then we currently get a flurry of error
emails and the users hitting the site then see an ugly Internal Server
Error page. This middleware catches ConnectionError (from requests)
and HttpServerError 503 (from slumber) and presents an error page in the
site's style saying the service is temporarily down.
PopIt and YourNextMP are being indepedently monitored by PopIt, so
hopefully this shouldn't affect our awareness of the site being down.
Fixes #126
> Add middleware to handle errors better if PopIt is down

- candidates/templates/candidates/person-view.html
- candidates/views/people.py
The rel="canonical" link should begin https://yournextmp.com so that the
old yournextmp.mysociety.org URLs are dropped from search engines; this
commit builds that URL with request.build_absolute_url.
This relies on the domain being correctly set in the sites framework
and request.is_secure() correctly reflecting whether the site's being
accessed over TLS.
> Change canonical URLs to include https://yournextmp.com

- candidates/middleware.py
- candidates/tests/fake_popit.py
- candidates/tests/test_person_view.py
We were getting error emails whenever a crawler tried to fetch a page
for a person who had been deleted, which was annoying. This was because
when slumber got a 404 from PopIt, it would raise a HttpClientError
exception. If we catch this and raise one of Django's Http404 exceptions
we shouldn't get an error email.
Fixes #211
> Catch 404 exceptions from PopIt and make sure 404 is returned

- candidates/forms.py
- candidates/models.py
- candidates/templates/candidates/person-view.html
- candidates/tests/test_create_person.py
- candidates/tests/test_csv_export.py
- candidates/tests/test_get_data_for_popit.py
- candidates/tests/test_new_person_view.py
- candidates/tests/test_update_person.py
- candidates/tests/test_update_view.py
- candidates/views/people.py
Some people have been adding titles like "Cllr" into their names; this
isn't good since most people don't have titles added, and ideally we'd
like to keep them separate.  The Popolo spec suggests honorific_prefix
and honorific_suffix for titles and post-nominal letters:
http://www.popoloproject.com/specs/person/name-component.html
This commit adds optional fields for these.
To avoid breaking CSV parsers that only look for column number (rather
than the field names in column headers) these are added to the end of
each row.
> Add fields for pre-nominal and post-nominal honorifics

- moderation_queue/forms.py
- moderation_queue/migrations/0004_queuedimage_why_allowed.py
- moderation_queue/migrations/0005_migrate_data_to_why_allowed.py
- moderation_queue/migrations/0006_auto_20150303_0838.py
- moderation_queue/models.py
- moderation_queue/static/moderation_queue/css/.gitignore
- moderation_queue/static/moderation_queue/css/photo-upload.scss
- moderation_queue/templates/moderation_queue/_photo-upload-form.html
- moderation_queue/templates/moderation_queue/photo-review.html
- moderation_queue/templates/moderation_queue/photo-upload-new.html
- moderation_queue/tests/test_queue.py
- moderation_queue/tests/test_upload.py
- moderation_queue/views.py
- mysite/settings.py
People seemed to be sometimes checking all of the boxes without
understanding what they meant, since some are mutually exclusive.
This commit switches the BooleanField fields in the model for why a
photo should be allowed to be used for a CharField with defined
choices.
It also removes use of the phrase "public domain" from the text
the user sees, since that's apparently widely misunderstood.
The photo upload form now looks like:
(although i've now fixed the "selection of these options" typo)
Fixes #228
> Make the choices of why photos are allowed mutually exclusive

- candidates/forms.py
- candidates/middleware.py
- candidates/migrations/0002_usertermsagreement.py
- candidates/migrations/0003_create_user_terms_agreements.py
- candidates/models.py
- candidates/static/candidates/_copyright-assignment.scss
- candidates/static/candidates/style.scss
- candidates/templates/candidates/ask-for-copyright-assignment.html
- candidates/tests/auth.py
- candidates/tests/test_new_person_view.py
- candidates/tests/test_terms_agreement.py
- candidates/tests/test_update_view.py
- candidates/urls.py
- candidates/views/__init__.py
- candidates/views/agreement.py
- candidates/views/mixins.py
- moderation_queue/tests/test_queue.py
- moderation_queue/tests/test_upload.py
- moderation_queue/views.py
- mysite/settings.py
As part of our plan to make sure that the licensing of the YourNextMP
database is clear, we've been recommended to ask for copyright
assignment from contributors.
This pull request introduces changes such that authenticated users
won't be able to view pages unless they either:
* Agree to the copyright assignnment
* or Log out
The text of the copyright assignment agreement is currently:
---
Before you carry on to edit data in YourNextMP, we need you to agree that your contributions to this site (with the exception of photo uploads) are owned by Democracy Club Limited. In return, we agree to make the complete database available under an open licence such as CC-BY-SA or remove copyright restrictions by releasing into the public domain (CC0).
❏ **Yes, I agree to assign the copyright of my …
> Ask authenticated users to agree to copyright assignment

- candidates/templates/candidates/about.html
Previously the agreement with our users was a paragraph
on the About page. Now we've introduced a click-through
agreement to do copyright assignment, we need to remove
this old and problematic wording. That's done in: e89f9d5
The other key change is to make a one-off snapshot CC0
release of the data up to this point; essentially we're putting
the data up to this point into the public domain, which we
said in the previous agreement we might do, and then
further contributions on top of that will be unambiguously
owned by Democracy Club. This includes a warning that
this snapshot will rapidly become out of date, and a
strong suggestion that users should use the up-to-date
data instead. That's done in 76aa714.
There are also various other small edits to improve the
clarify of this page.
> Update "About" page now we have a better contributor agreement

- candidates/templates/candidates/ask-for-copyright-assignment.html
It is possible to assign future copyright. Hence saying "I assign ..." will assign future copyright whereas "I agree to assign ..." may be interpreted as meaning that I agree to execute an assignment in the future. Until I actually do assign, there is no assignment of the legal rights in the copyright. Obscure and unlikely to be essential, but I would prefer it as a tweak.
> Strengthened language of assignment

- candidates/templates/candidates/person-view.html
I've seen a significant number of cases of edits by candidates where they seem to think that "Official party page" means their party homepage and put in the URL of their party's main website.
I've updated the wording to bring it more in line with the person edit form, to say "Party PPC page", which I think is more obvious.
> change wording in person-view for PPC page link

- candidates/management/commands/candidates_fix_image_metadata.py
- candidates/management/commands/candidates_remove_bogus_dates.py
- candidates/management/commands/candidates_remove_last_party_from_versions.py
- candidates/update.py
- conf/packages
- moderation_queue/tests/test_queue.py
- moderation_queue/views.py
- requirements.txt
Bugs at various stages have introduced some extra fields, and the image
metadata has been through various changes; these commands are one-off
scripts that should clean these up.
> Add commands to clean up bogus data in the YourNextMP PopIt

- candidates/management/commands/candidates_update_popit_parties_from_ec_data.py
Andy wrote:
> Regarding the party logo, we currently use the primary graphic held by the Electoral Commission. The logo you sent is on file with the Electoral Commission, so I have contacted our developers to see if it’s a possibility to use that one instead. It’s likely it will be necessary to use the same graphic for all party members – is that okay?
TUSC candidate wrote:
> Yes, I think that would be good. This is the one that is being used by a majority of the candidates. 
Refs #265.
> Hardcode TUSC image to use

- candidates/views/constituencies.py
ElectionLeaflets.org constituency URLs have moved from e.g.:
https://electionleaflets.org/constituencies/oxford_west_and_abingdon
to:
https://electionleaflets.org/constituencies/65564/oxford_west_and_abingdon
> Fix link to ElectionLeaflets.org

- candidates/update.py
- moderation_queue/models.py
- moderation_queue/static/moderation_queue/css/crop.css
- moderation_queue/static/moderation_queue/css/crop.scss
- moderation_queue/static/moderation_queue/js/crop.js
- moderation_queue/templates/moderation_queue/photo-review.html
- moderation_queue/tests/test_queue.py
- moderation_queue/views.py
This pull request:
* Shows the already uploaded images of the candidate on the photo review page
* Adds an "ignore" option when reviewing photos (e.g. when someone has uploaded a duplicate)
> Some small improvements to the photo review page

- auth_helpers/migrations.py
- auth_helpers/templates/auth_helpers/group_permission_denied.html
- auth_helpers/views.py
- candidates/migrations/0004_add_trusted_to_merge_group.py
- candidates/models.py
- candidates/templates/candidates/person-edit.html
- candidates/views/people.py
- moderation_queue/migrations/0008_add_photo_review_permissions.py
- moderation_queue/models.py
- moderation_queue/tests/test_queue.py
- moderation_queue/views.py
- mysite/settings.py
Previously, the only way we could give additional permissions to users on the
site was to make them staff or a superuser; these both need you to put a lot
of trust in the users, since they confer other abilities (e.g. to see other users'
email addresses).
This commit introduces two groups called 'Photo Reviewers' and 'Trusted To
Merge' which we can selectively add users to if we trust them to help out with
those tasks.
> Finer-grained permissions for merging candidates and reviewing photos

- moderation_queue/forms.py
- moderation_queue/static/moderation_queue/js/crop.js
- moderation_queue/templates/moderation_queue/photo-review.html
- moderation_queue/tests/test_queue.py
- moderation_queue/views.py
Sometimes it's clear that the uploaded image is a better one to
use for the candidate, while sometimes it's just an extra one that
it might be nice to have.  Previously, all approved photos were
appended to the images array, which meant they wouldn't be used.
This commit changes that, so that now there's a "make this the
primary image" option, which, when selected, will insert that image
at the front of the images array.
Fixes  #250
> Add a "make this the primary image" option when reviewing a photo

- candidates/static/candidates/_header.scss
- candidates/views/people.py
- mysite/context_processors.py
- mysite/settings.py
- mysite/templates/base.html
Like this:
As well as a reminder for how many photos there are still
for review, this provides a link to the review queue on every
page for users who are able to do something about that.
> Add notification of number photos for review

- mysite/settings.py
The Django cache middleware also adds a Vary: Cookie header to
responses, so this should mean that Varnish can serve cached
versions of these pages for 20 minutes to client that aren't
sending cookies.
> Add Cache-Control headers with max-age 20 of minutes

- candidates/templates/candidates/finder.html
- candidates/tests/test_finders.py
- candidates/views/frontpage.py
Having {% csrf_token %} in a template causes a cookie to be set when
viewing that page, which will mean pages of the site won't be cached
across different anonymous users because of Vary: Cookie header.
One option would be to change the postcode and constituency lookup
forms to have action="get" and leave out the CSRF token, but this
would mean some slightly complicated changes to the class-based
views; it's easiest just to exempt those views from CSRF protection
and remove the {% csrf_token %}.  (This shouldn't have any security
implication for these views, since they're just looking up public
information.)
> Don't set the csrftoken cookie from the front page

- candidates/management/commands/candidates_fix_image_metadata.py
- candidates/management/commands/candidates_remove_bogus_dates.py
- candidates/management/commands/candidates_remove_last_party_from_versions.py
These one-off scripts were introduced to fix problems in that data that
meant that indexing of people in Elasticsearch would fail, but had some
bugs in them. Now that https://github.com/mysociety/popit/issues/814 and
https://github.com/mysociety/popit/issues/794 are resolved, it's worth
fixing these so we can try again.
This is related to https://github.com/mysociety/yournextmp-popit/issues/295
> Fix the "fix data" commands

- cached_counts/management/commands/cached_counts_create.py
We've made an effort recently to get rid of all the parties that are now
dissolved, and we now only consider the current parties when counting
numbers of candidates for each party. However, there will still be rows
in the cached_counts_cachedcount table that refer to now-dissolved
parties.
This commit introduces code to purge any such dissolved parties from the
cached_counts_cachedcount table when cached_counts_create is run.
Fixes #260
> Remove any dissolved parties from /numbers/parties

- candidates/forms.py
- candidates/templates/candidates/person-view.html
- candidates/tests/test_create_person.py
- candidates/tests/test_update_person.py
- candidates/update.py
- candidates/views/people.py
- requirements.txt
Allows the editing form to accept a date of birth or year of birth (the label still says 'Date of birth' but the help text will say 'YYYY-MM-DD or YYYY'.
As a result, age will be displayed as 'n-1 or n' if we've just got a year as we can't determine the exact age with any certainty (similar to Wikipedia behaviour but I can't find an example now that I want one).
Fixes #246
> Allow birth year as an alternative to full dob

- candidates/templates/candidates/constituency.html
Occasionally, statement of nominations are updated, and a new version needs to be uploaded e.g.
https://yournextmp.com/constituency/65845/bexhill-and-battle
To do this, you currently need to know the statement of nominations upload URL i.e.:
https://yournextmp.com/upload_document/upload/[constituency ID]/
A permanent link to this is therefore handy.
> Add a permanent Noms upload link

- moderation_queue/templates/moderation_queue/photo-review.html
- moderation_queue/views.py
- requirements.txt
It's useful to be able to follow links that people quote in the
"justification for use" box, but we have to sanitize anything in that
box before linkifying anything URL-like and marking it safe.
> Use bleach to clean & linkify 'justification for use' text in photo review

- mysite/templates/base.html
We're shortly going to move the crowd-sourcing interface to
edit.yournextmp.com while a static site is served at yournextmp.com.
This changes the Google Analytics tracking code as advised here:
https://support.google.com/analytics/answer/1034342?hl=en
... for this site being the secondary domain to yournextmp.com
I'm unclear about whether it would be bad to deploy this before
changing this site to be edit.yournextmp.com (i.e. whether it would
lose us analytics events) but I would hope not.
> Update Google Analytics for this being on a secondary domain

- candidates/templates/candidates/party.html
- candidates/tests/test_party_pages.py
- candidates/views/parties.py
It didn't make sense to just show a long list of constituencies saying
"no party standing here" for almost all of them, so this commit changes
the party pages so it only shows all constituencies in a country for
parties standing candidates in more than 30% of the seats there.
> On party pages, only show every constituency for the biggest parties

- tasks/templates/tasks/field.html
This also removes the search without constituency name – just
because I’m not really sure we need both.
> Use fieldname in default search

- candidates/management/commands/candidates_add_new_parlparse_ids.py
We'd like to link through to the TheyWorkForYou pages for all new MPs
from YourNextMP, but for people who have never been in TheyWorkForYou
previously, we won't have a parlparse / TWFY ID for them. This script
will fetch parlparse's people.json and look for any people in there
who have a yournextmp identifier, and check that we have the correct
parlparse ID for that person, updating it if it was missing.
> Fetch any parlparse (TheyWorkForYou) IDs for newly elected MPs

- conf/general.yml-example
- mysite/account_adapter.py
- mysite/settings.py
As we get closer to the election and the site gets more attention, it
presumably is more likely to attract malicious editors. This commit
prevents new accounts from being created, but still allows existing
users to log in.
> Prevent any new user accounts from being created

- candidates/templates/candidates/constituency.html
- candidates/templates/candidates/frontpage.html
- candidates/templates/candidates/person-view.html
- candidates/templatetags/metadescription.py
- candidates/views/frontpage.py
- candidates/views/people.py
- elections/uk_general_election_2015/templates/candidates/finder.html
- elections/uk_general_election_2015/views/frontpage.py
- locale/en/LC_MESSAGES/django.po
- locale/es_AR/LC_MESSAGES/django.po
- mysite/context_processors.py
- mysite/settings.py
Adds per app `SITE_NAME`, `SITE_DESC `, `SITE_TWITTER` and `SITE_LOCALE` settings which are used in the Twitter and OpenGraph metadata rather than hardcoding "General Election", "en_GB" etc
Also removes "(PPCs) " from the metadata text.
Closes #383
> Make OpenGraph and Twitter metadata generic

- cached_counts/models.py
- cached_counts/templates/attention_needed.html
- cached_counts/templates/reports.html
- cached_counts/tests.py
- cached_counts/urls.py
- cached_counts/views.py
These are the posts ordered by the number of candidates, from
lowest to highest; this is a reasonable proxy in many cases for
those that need most attention from contributors.
This has been particularly requested for Argentina.
This is part of the work to fix #404 (the other bit is to include the
first few items from this list on the front page).
> Add a page showing the posts with most attention needed

- candidates/example-popit-data/posts_65730_embed=membership.person.membership.organization.json
- candidates/templates/candidates/_candidates_for_post.html
- candidates/tests/test_areas_view.py
- locale/en/LC_MESSAGES/django.po
- locale/es_AR/LC_MESSAGES/django.po
This seemed to just be a case of adding a second version of the button which would only be displayed if the user isn't allowed to edit (assume not logged in). Could just as easily become an only show button if statement.
Includes updated .po files which I had expected to just add "Sign in to add a new candidate" and yet... Hmmm. Will take that under advisement
Closes #388
Closes #408
> Fix the add candidate button

- candidates/models/popit.py
- candidates/tests/test_create_person.py
The cache of post (with embedded memberships, people and organizations)
wasn't being invalidated properly on creating new people, in particular
when a new person was created or had their membership of posts changed.
> Update the posts to be invalidated any time standing_in is changed

- candidates/forms.py
- candidates/popit.py
- candidates/tests/test_validators.py
- candidates/views/areas.py
- candidates/views/constituencies.py
- elections/uk_general_election_2015/lib.py
Previously, the post field (previously "constituency field") was only
ever a hidden field, since its value was always known - the add person
field was embedded in the area or post page, or it was brought up when
complaining about validation errors, in which case the field's value
was carried over.  Now we want to be able to link to the 'person-create'
page to allow people to add a new candidate to any post in an election
so we add a 'hidden_post_widget' keyword argument to indicate that the
form is being embedded with a supplied post_id.
Fixes #419
> Support either a hidden or usable post field on the person form

- candidates/models/popit.py
- candidates/tests/test_create_person.py
Thanks to Matthew Somerville for spotting this still used UK-specific
terminology.
> Remove 'PPC' from the link key for a party candidate page

- CONTRIBUTING.md
If there's a file of this name, GitHub will present it prominently
on creating a new issue or pull request, as described here:
https://github.com/blog/1184-contributing-guidelines
> Add a CONTRIBUTING.md guide for anyone contributing to the project

- candidates/models/auth.py
- candidates/models/popit.py
It makes sure to always return a dictionary no matter what might be
stored. Also check we have some standing_in contents before testing a
lock on it.
Might fix #475
> Try and always use standing_in property.

- bin/pre-deploy
Only install sass (compass isn't needed) and only install it if the
required version isn't already present.
Fixes #469
> Simplify gem installation

- mysite/settings.py
The keys used in the memcached backend are based on the database name
(so that multiple instances of the application on the same host can
use the same memcached); however, in the case where you're using
sqlite as a database, the name of the database will be the path to
the sqlite database file.  This was based on BASE_DIR in
mysite.settings, which didn't canonicalize the path, so sometimes
the path to the database would be relative and sometimes absolute.
This meant that values stored in memcached couldn't be reliably
retrieved.
We think this is probably the reason that collecstatic would sometimes
appear not to update the cache of fingerprinted filenames, and may
also explain why cache invalidation for posts seems to be failing on
the instance for Argentina.
This commit introduces a …
> WiP: Canonicalize BASE_DIR, which should fix some caching issues

- bin/pre-deploy
- candidates/static/js/constituency.js
- candidates/static/js/versions.js
- elections/ar_elections_2015/templates/base.html
- locale/en/LC_MESSAGES/djangojs.po
- locale/es_AR/LC_MESSAGES/django.po
- locale/es_AR/LC_MESSAGES/djangojs.po
- mysite/settings.py
- mysite/templates/generic_base.html
- requirements.txt
This allows translation of the three strings present in JavaScript,
using Django's built in functionality and a third party module to
create static versions of the output on deploy.
Fixes #463 (the remaining string).
> Add JavaScript translation capability.

- candidates/tests/test_merge_view.py
- candidates/views/people.py
When we refactored to add more functionality to the PopItPerson class,
the history of merged candidates became broken - it was missing the
history from the secondary person in the merge. This fixes the test and
makes sure that version history is appended.
Fixes #376
> Fix the versions array that's recorded after a merge

- elections/ar_elections_2015/settings.py
When viewing the national pseudo-area, at the URL /areas/NAT-0, the
code tries to find a post with ID 'pres' based on the post_id_format
in elections/ar_elections_2015/settings.py - however, the ID in
PopIt and in the rest of the code is 'presidente', so the post isn't
found.  The UnknownPostException is caught and (confusingly)
reported as a malformed area error.
This should be fixed just by changing the post_id_format for the
presidential post in the settings file, as this commit does.
Thanks to Matthew Somerville (@dracos) for diagnosing this problem
while I was away.
> AR: Fix the UnknownPostException when viewing /areas/NAT-0

- cached_counts/tests.py
- candidates/example-popit-data/search_mp_posts_page=1.json
- candidates/tests/test_constituency_lock.py
- candidates/tests/test_create_person.py
- candidates/tests/test_finders.py
- candidates/tests/test_merge_view.py
- candidates/tests/test_posts_view.py
- candidates/tests/test_rename_restriction.py
This finishes the work of mocking and patching network-dependent
functionality in tests so that they don't rely on any external APIs.
Fixes #448
> Make the tests network-independent again

- candidates/management/commands/candidates_create_popit_organizations.py
- candidates/management/commands/candidates_create_popit_posts.py
These are two generically useful commands which were only in the
Argentinian elections app - this PR moves them into the core
'candidates' app. (The only special case for Argentina is in fact
not needed.)
> Move generic popit creation commands into the 'candidates' app

- .gitignore
- bin/pre-deploy
- mysite/settings.py
- requirements.txt
The "./manage.py compilejsi18n" command just writes the djangojs.js
files under STATIC_ROOT rather than being processed by
staticfiles, so the fingerprinted versin of this file is never
ceated. It seems that to get staticfiles to process the output of
compilejsi18n you have to follow one of these approaches:
https://django-statici18n.readthedocs.org/en/latest/faq.html#how-to-configure-static-files-with-django-statici18n
Since we already have mysite/static added to STATICFILES_DIRS this
commit takes the latter approach and gets compilejsi18n to output
to mysite/static/jsi18n/...
We also alter the order of the commands in bin/pre-deploy so that
these files are generated before collectstatic is run.
Fixes #525
> Fix so that the fingerprinted djangojs.js files can be found

- candidates/templates/candidates/_person_update_call_to_action.html
- candidates/tests/test_flash_calls_to_action.py
- candidates/views/people.py
- mysite/templates/generic_base.html
As discussed with @struan / @duncanparkes in IRC, the function to create
this message was less than clear - hopefully switching that to use a partial
template helps with that.
This also fixes a long-standing bug in the rendering, where the flash
message was shown as:
... instead of:
> Updates to the call-to-action flash message after updating / creating a person

- candidates/example-popit-data/generic_posts_embed=.json
- candidates/example-popit-data/search_mp_posts_page=1.json
- candidates/management/commands/candidates_create_popit_posts.py
- candidates/popit.py
The previous change (e9a502a0b) to store an 'election' attribute on
each post actually wasn't quite right, because people can be elected
to the same post in more than one election.  (The example we have at
the moment is that the UK site has both a 2010 and 2015 election
with exactly the same posts.)  The previous change meant that the
UK general election posts only ended up associated with one election
when they should be returned from searches for both.
This commit changes that, so that posts are expected to have a
'elections' array of election IDs instead of an 'election' string
with a single election ID.
After deploying this, you will need to run:
./manage.py candidates_create_popit_posts
... to make sure all the posts have the correct 'elections' attribute.
> Posts need an 'elections' array attribute, not an 'election' string

- cached_counts/templates/reports.html
- candidates/middleware.py
- candidates/templates/candidates/_person_update_call_to_action.html
- candidates/templates/candidates/ask-for-copyright-assignment.html
- candidates/templates/candidates/popit_down.html
- docs/transifex.md
- elections/uk_general_election_2015/templates/candidates/ask-for-copyright-assignment.html
- locale/cy_GB/LC_MESSAGES/django.po
- locale/en/LC_MESSAGES/django.po
- locale/es_AR/LC_MESSAGES/django.po
- locale/fr/LC_MESSAGES/django.po
- moderation_queue/templates/moderation_queue/photo_approved_email.txt
- moderation_queue/templates/moderation_queue/photo_rejected_email.txt
- moderation_queue/tests/test_queue.py
- moderation_queue/views.py
- mysite/settings.py
- mysite/templates/account/login.html
- mysite/templates/generic_base.html
@evz pointed out that running `./manage.py makemessages` generates lots
lots of spurious changes because it was wrapping lines in the .po files; this
makes it really annoying for contributors to update translations when they
add a new string for localization. This pull request should fix that issue by
standardizing on not word-wrapping either the `msgid` or `msgstr`.
> Fix translation formatting

- candidates/election_specific.py
- candidates/mapit.py
- candidates/tests/test_upcoming_elections_api.py
- candidates/urls.py
- candidates/views/api.py
- elections/uk_general_election_2015/lib.py
Add an API to list some basic information for the upcoming elections at a postcode or co-ordinate.
The API lists all the positions for which there will be an election in the future, along with details of the area the post is for and the election it is part of. It uses the election_date property of the election to determine which elections to display.
If an election does not have an election_date then it won't be displayed.
Fixes #581
> Upcoming elections api

- elections/cr/data/parties.csv
- elections/cr/management/commands/cr_import_parties_from_csv.py
Management command and accompanying CSV file for importing a list of parties and generating the related party sets for the 2016 Costa Rica municipal elections.
Takes an argument of a CSV file which should have 3 columns:
1: Name of party
2: ID of party (optional)
3: Comma separated list of Cantons the party is standing in
The ID is the "Cédula Jurídica" and is added as an Identifier.
It expects the CSV file to have NO header row.
It will create, or update, a party for each row in the CSV and a party set for each Canton, adding the party to the party sets for the Cantons in which the party is standing.
This generates slugs by slugifying the party name as we don't have the above IDs for all parties.
If you run
```
/manage.py candidates_create_party_list_from_ep …
```
> Import list of Costa Rica parties from CSV file

- tasks/templates/tasks/field.html
- tasks/tests/test_views.py
- tasks/views.py
If there were no candidates (e.g. when the site's first launched)
there would be a divide-by-zero on viewing, say /tasks/email
Thanks to Accesa for reporting this bug.
> Fix a divide-by-zero error in /tasks/{whatever}

- candidates/templates/candidates/frontpage.html
- candidates/templates/candidates/recent-changes.html
Rather than use the candidate ID on the list of recent changes use the
name of the candidate which makes it a bit more human friendly
Fixes #621
> change candidate id to name on front page recent changes list

- candidates/templates/candidates/person-view.html
- conf/general.yml-example
- mysite/context_processors.py
- mysite/settings/conf.py
The 'S' format specifier for dates is:
"English ordinal suffix for day of the month, 2 characters."
https://docs.djangoproject.com/es/1.9/ref/templates/builtins/#date
It doesn't make sense having the "th" suffix on a date in Spanish,
for example.
Fixes #631
> Fix non-internationalizable ordinal suffix for day of the month

- candidates/forms.py
- candidates/models/__init__.py
- candidates/models/popolo_extra.py
- candidates/tests/test_date_parsing.py
- candidates/tests/test_update_view.py
- conf/general.yml-example
- mysite/settings/conf.py
The change introduced by this commits allows many more date formats
than previously, when just YYYY or YYYY-MM-DD was allowed.
There's also a new DD_MM_DATE_FORMAT_PREFERRED configuration option
to control whether to use the USA or rest-of-the-world date formatting
preference.
Fixes #165, hopefully fixes #444
> Make date-of-birth parsing more liberal

- candidates/static/candidates/_people.scss
- candidates/templates/candidates/person-view.html
The `key-value-list` class stacks a `<dl>` element’s contents vertically, limiting the width of the `<dt>` elements inside and truncating them with an ellipsis if they over-run.
This is mostly ok in English (but not always!) but is a real problem in other languages where important labels get truncated because they’re too long, and there’s no way to reveal the full text.
This commit removes the `key-value-list` class from the `<dl>` elements on the candidate profile page, so the `<dt>` and `<dd>` elements will just stack vertically, as normal.
The CSS rules are left intact, in case re-users want to add the class back into their custom templates.
> Remove `key-value-list` class from core profile page list elements

- candidates/forms.py
- candidates/models/popolo_extra.py
- candidates/tests/test_date_parsing.py
- candidates/tests/test_new_person_view.py
The commit that added dateutil.parser for parsing otherwise
unrecognised dates (507055baf) unfortunately also handled the
empty string and interpreted it as today's date, so not filling
in the date of birth field would give someone today's date as
their birthday.  This commit fixes that and adds regression
tests.
> Fix bug where blank birth date was interpreted as today

- bin/pre-deploy
- conf/packages
Because of this bug:
https://github.com/pennersr/django-allauth/issues/1032
... we need to manually compile the allauth .po files into
.mo files.
> Make sure allauth's .po files are compiled on deploy

- candidates/admin.py
- candidates/forms.py
- candidates/management/commands/candidates_import_from_live_site.py
- candidates/migrations/0015_add_configurable_extra_fields.py
- candidates/migrations/0016_migrate_data_to_extra_fields.py
- candidates/migrations/0017_remove_cv_and_program_fields.py
- candidates/models/__init__.py
- candidates/models/fields.py
- candidates/models/popolo_extra.py
- candidates/serializers.py
- candidates/templates/candidates/person-edit.html
- candidates/templates/candidates/person-view.html
- candidates/tests/test_extra_fields.py
- candidates/urls.py
- candidates/views/api.py
- candidates/views/people.py
- elections/bf_elections_2015/settings.py
- mysite/settings/conf.py
We added hard-coded special cases for the 'CV' and 'Program' fields
to add them for Burkina Faso.  This was pretty ugly and not nice to
maintain as we add different additional (non-Popolo) fields for other
countries. For example, Costa Rica want a "Profession" field.
This pull request allows you to add additional fields in the admin
interface which anyone can then edit in the usual way on the site.
Still to do:
bf_elections_2015 then the `cv` and `program` fields
are added to the database.
`program` from the codebase.
then the `profession` field is added.
additional fields
> Add generic support for additional fields

- candidates/forms.py
- candidates/models/popolo_extra.py
- candidates/tests/test_date_parsing.py
- requirements.txt
This should fix handing dates in the translated language and also slightly more fullsome date descriptions like '20 de febrero de 1954'
It does this by adding a parserinfo class with translated month names that is then passed into dateutils.parse to change the set of strings it uses to match months. This uses ugettext_lazy as otherwise the translation is done at module load time which may be before language settings have been changed.
> Fix date parser errors with Spanish

- candidates/templates/candidates/person-view.html
- candidates/views/people.py
If there are 2 or fewer elections known to the site, it's probably
fine to show whether they're standing in both.  However, when there
are more elections, this begins to look weird - in the UK elections
in 2016, there'll just be a list of 10 or so "don't know" indications
in the "Constituencies" section.
So, this commit makes that cut-off, and if there are more than 2
elections known to the site, just shows the constituencies someone's
known to be standing in (or did stand in).
This also changes the section heading to "Candidacies" which is more
general than "Constituencies", and hopefully just as clear.
Fixes #472
> Person page: don't show a big list of elections they're not standing in

- bin/pre-deploy
- candidates/static/candidates/_content.scss
- mysite/settings/conf.py
Fixes #537.
Versions of Sass greater than 3.2.19 would raise an exception (via Django pipeline) when attempting to `@extend` the `.radius` selector from Foundation.
`@include`-ing Foundation’s `radius()` mixin seems to work instead.
---
@mhl – I think this PR fixes the error from the original ticket, but I’m getting pretty broken looking styles in its place. I can't tell whether it's the new line of code (unlikely) or whether it's just a broken dev environment.
> Avoid Sass compiler error when extending .radius

- candidates/admin.py
- candidates/forms.py
- candidates/management/commands/candidates_import_from_live_site.py
- candidates/migrations/0021_simplepopolofield.py
- candidates/migrations/0022_create_standard_simple_fields.py
- candidates/models/__init__.py
- candidates/models/fields.py
- candidates/models/popolo_extra.py
- candidates/models/versions.py
- candidates/serializers.py
- candidates/templates/candidates/person-edit.html
- candidates/templates/candidates/person-view.html
- candidates/tests/test_simple_fields.py
- candidates/urls.py
- candidates/views/api.py
- candidates/views/people.py
- mysite/extra_translations.py
This adds a table with a list of the simple PopoloFields that should be displayed on the site and then uses that list to determine which fields to display.
The set of fields is restricted to those that are part of the Popolo spec and are direct properties of the Person object.
NB: at the moment the Patronymic name isn't displayed anywhere because it's not clear how to do so.
This fixes #663
> Customize visible fields

- elections/uk/management/commands/uk_create_mayoral_posts.py
This is classed at WIP because I expect we'll need to figure out election groupings as part of this PR, or soon after.
Mayors are absolutely different elections, with their own IDs, however it's not very logical to list them differently on the site.  It could be that this is a very simple change to `posts.html`, or there might be something more complex.  mysociety/yournextrepresentative#598 talks about this more.
For now, I think this script imports the Mayors correctly, with different election IDs, making it technically "done"
> Mayoral Election importer

- candidates/views/people.py
It's not really clear why this was hardcoded, but it's not helpful now we have more than a single election.  
Later on, we need to think about this properly, so that it knows what elections are correct to show.
For now, let's just remove it.
> Remove election_to_show from the context

- candidates/views/api.py
DRF's default is to assume that a slug wont have a '.' in it.  UK Election IDs do have '.' in them, and are used as slugs, thus breaking the API with the defaults.
> Force Django REST Framework to support slugs containing '.'.

- cached_counts/models.py
- cached_counts/views.py
- candidates/admin.py
- candidates/management/commands/candidates_create_areas_and_posts_from_mapit.py
- candidates/management/commands/candidates_import_from_live_site.py
- candidates/migrations/0023_create_post_to_elections_m2m_with_extra_fields.py
- candidates/migrations/0024_port_existing_post_to_election_m2m_data.py
- candidates/migrations/0025_remove_old_post_to_election_m2m_and_rename_new.py
- candidates/models/__init__.py
- candidates/models/popolo_extra.py
- candidates/tests/factories.py
- candidates/tests/test_record_winner.py
- candidates/views/constituencies.py
- elections/cr/management/commands/cr_create_basic_site.py
- elections/jamaica/management/commands/jamaica_create_basic_site.py
- elections/uk/management/commands/uk_create_mayoral_posts.py
- elections/uk/management/commands/uk_create_pcc_posts.py
- elections/uk/management/commands/uk_create_regional_assembly_posts.py
Allow the number of winners in an election to be set on a per post level by using a custom M2M model between PostExtra and Election.
For #691
> Customize winner count per post

- candidates/views/api.py
- mysite/settings/conf.py
- requirements.txt
This fixes #744 and should obviate the need for https://github.com/DemocracyClub/yournextrepresentative/commit/84b9391ac9b875ff566d93c40ac66aa1661a747d
> Add a "current" filter for the elections API and page size customization

- candidates/admin.py
- candidates/forms.py
- candidates/migrations/0026_complexpopolofield.py
- candidates/migrations/0027_create_standard_complex_fields.py
- candidates/models/__init__.py
- candidates/models/fields.py
- candidates/models/popolo_extra.py
- candidates/models/versions.py
- candidates/templates/candidates/_person_form.html
- candidates/templates/candidates/areas.html
- candidates/templates/candidates/person-view.html
- candidates/tests/test_areas_view.py
- candidates/tests/test_complex_fields.py
- candidates/tests/test_new_person_view.py
- candidates/views/helpers.py
- candidates/views/people.py
This allows people to add custom fields based on contact details and links where the underlying data is stored in a related table and not as a direct property of the person.
The setup of them does require knowing what you are doing but there are hints in the admin interface to make it a bit easier.
It also has a migration to set up the standard fields that all existing YNR install have.
Fixes #683
> Customize complex fields

- requirements.txt
The following error is produced when using the Google social login:
SSLError: [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
... from requests.  I believe that this error is due to the servers we
(and Democracy Club) currently run having OpenSSL 1.0.1 and using a recent
version of the certifi Python package (which contains root
certificates).
A full explanation can be found here:
https://github.com/certifi/python-certifi/issues/26
(found via: http://stackoverflow.com/a/34665344/223092 )
Since upgrading OpenSSL to 1.0.2 will be a pain, pinning certifi to the
old version is the easiest way to fix this error for the moment.
Hopefully we will upgrade the distributions on our servers in the near
future to one that supplies OpenSSL 1.0.2 and …
> Fix for Google social login SSL error

- elections/uk_redirect_to_dc/settings.py
- elections/uk_redirect_to_dc/urls.py
- elections/uk_redirect_to_dc/views.py
We want to redirect all requests to edit.yournextmp.com to Democracy
Club's candidates site (https://candidates.democracyclub.org.uk) from
now on.  This adds a new country we can switch edit.yournextmp.com to
use which will just redirect.
> Add a country that just redirects to Democracy Club's site

- candidates/views/frontpage.py
The logic here was wrong, so it would think there were no results
at all if the first query to MapIt returned some, but the second query
returned none.
Combined with errors in the MapIt generation data in the DC install
of YNR this meant that any geolocation query would say "Your location
does not seem to be covered by this site".
Partial fix for #751
> Fix the GeoLocatorView for multiple MapIt generations

- candidates/models/popolo_extra.py
This test was broken - if an ImageExtra is missing, then
django.db.models.fields.related.RelatedObjectDoesNotExist is raised.
Catch the exception superclass for objects that don't exist instead.
> Fix a test for whether an ImageExtra exists in CSV generation

- candidates/templates/candidates/_candidates_for_post.html
- candidates/views/helpers.py
It turns out to be nice to have a link to the party list even if the
list of candidates isn't truncated.
> Display the party list link even if the people list isn't truncated

- mysite/settings/conf.py
Unicode escapes inside 'bare' strings are not understood by
``xgettext``, the utility that creates translatable strings
from Python source code.  The backslash would be doubled in the
.po file; '\u2014' ≠ '\\\u2014'; and no translations
would then be found for 'SOURCE_HINTS'.
> Restore the ``u`` prefix in 'SOURCE_HINTS'

- candidates/models/popolo_extra.py
- candidates/tests/test_missing_fields.py
e.g. you can find all those without a Twitter username with:
PersonExtra.objects.missing('twtiter_username')
... or those missing a date of birth with:
PersonExtra.objects.missing('birth_date')
Hopefully this will be useful for building task-focussed pages on YNR
sites.
> Add a PersonExtra queryset method to find people with missing data

- candidates/templates/candidates/person-view.html
The 'E' format character declines the month name.  See
https://docs.djangoproject.com/en/1.8/ref/templates/builtins/#date
Closes #817.
> Use 'format' form of month names in candidate birth date

- moderation_queue/static/moderation_queue/css/crop.scss
Previously, all of Foundation would be duplicated inside
'image-review' - some 250 KB - causing rendering issues.
> Lose the Foundation presentational classes in 'image-review'

- elections/uk/static/candidates/_finder.scss
3597b7e3022d9748422b45942077ca684b1a555f edited the `_finder.scss` styles in core, when really it should have been a UK-specific change.
This commit reverts those changes to core `_finder.scss`, and moves the `.finder__forms__container` and other related changes into a UK-specific override of the `_finder.scss` stylesheet.
Fixes #831.
@mhl – could you give this a review? I've tested it locally by switching to the `uk` country, but all I see on the homepage is the location search form, rather than the extra stuff that’s visible on https://candidates.democracyclub.org.uk. I’m assuming there's some democracy club magic that I'm missing?
> Fix "finder" styling on non-UK homepages

- candidates/static/candidates/_people.scss
``pre-line`` behaves the same way as ``normal``, save for
preserving new lines.  ``pre`` preserves new lines and repeated
spaces, and respects line length; it's what we'd use for
computer code.
> Wrap long lines in multi-paragraph extra fields

- candidates/templates/candidates/_candidates_for_post.html
- candidates/views/helpers.py
I  made this change for the UK, to respond to a request from @symroe 
and @JoeMitchell - it means that the big numerals that were present on
the party list pages will now be used on the post and area pages too.
I was unsure about whether this would be generally welcomed by all
redeployers of YNR, but I think it's quite nice having the numbers on all
pages that display party lists. Do you have a view on that, @wfdd ?
> Show big party list position numbers on post and area pages too

- candidates/models/popolo_extra.py
- candidates/tests/test_party_dropdown_ordering.py
- conf/general.yml-example
- mysite/settings/conf.py
A first pass at this - no tests yet, and it doesn't do the nice formatting
of right-aligning the candidate numbers as Zarino's sketch suggested,
but it's a start:
> Put the parties with the most candidates at the top of the party drop-down

- candidates/templates/candidates/_candidates_for_post.html
- candidates/tests/dates.py
- candidates/tests/factories.py
- candidates/tests/test_hide_record_winner_buttons.py
- candidates/tests/test_person_view.py
- candidates/tests/test_record_winner.py
These buttons add lots of visual clutter to the candidate lists, and are
only actually useful on election day or afterwards, so don't show them
until then.
Fixes #779
> Only include the record winner button on or after election day

- candidates/migrations/0029_add_ordering_to_fields_meta.py
- candidates/models/fields.py
- candidates/views/helpers.py
- candidates/views/people.py
This obviates the need to use ``order_by``, which we'd
forgotten to do with the Popolo fields in the person view.
> Sort person fields by their value of ``order`` by default

- candidates/templates/candidates/_candidates_for_post.html
The existing button will drop below the fold when the list
has grown sufficiently long.
> Repeat 'Add a new candidate' button at top of candidate list

- candidates/forms.py
- candidates/models/versions.py
- candidates/static/candidates/_forms.scss
- candidates/static/candidates/_people.scss
- candidates/static/js/constituency.js
- candidates/templates/candidates/_othername_form.html
- candidates/templates/candidates/_person_form.html
- candidates/templates/candidates/othername_edit.html
- candidates/templates/candidates/othername_list.html
- candidates/templates/candidates/othername_new.html
- candidates/tests/test_other_names.py
- candidates/tests/test_posts_view.py
- candidates/urls.py
- candidates/views/__init__.py
- candidates/views/other_names.py
Previously there was no support for adding, deleting or editing
alternative names for people in YNR, although this is supported by the
Popolo data model.
This commit adds basic support for editing alternative names for
people; the page for managing a person's other names is linked to
from the person edit page under their full name.
Fixes #749
Things still to do (although this is usable without them):
> Add support for editing alternative names for people

- candidates/models/versions.py
- candidates/tests/test_merge_view.py
This was a bug - the revert_person_from_version_data method,
which was used to implement merges of two candidates as well
as reverting them to an earlier version, deletes all existing
candidacies of a person and then recreates the ones that
should be there.  However, the code was only actually removing
the MembershipExtra objects and leaving the Membership objects
in the database.  These weren't shown on the user-facing site
because of missing the MembershipExtra objects, but would be
shown in the API output which was causing confusion.
This commit fixes that problem; a delete on the Membership
queryset deletes the corresponding MembershipExtras too.
Thanks to Sym Roe (@symroe) for spotting this and figuring
out that it related to merging.
Fixes #866
> On merging / reverting remove Memberships as well as MembershipExtras

- candidates/forms.py
- candidates/management/commands/candidates_update_twitter_usernames.py
- candidates/models/field_mappings.py
- candidates/models/popolo_extra.py
- candidates/tests/test_constituency_view.py
- candidates/tests/test_csv_export.py
- candidates/twitter_api.py
- conf/crontab.ugly
- conf/general.yml-example
- mysite/settings/conf.py
This pull request adds:
* A management command for looking for (and fixing) any mismatches
between Twitter screen names (in a ContactDetail with contact_type
'twitter') and user IDs (in an Identifier with scheme 'twitter'). The user
ID, if present is treated as the more reliable source (since it is - people
can change screen names, and their user ID will remain the same).
* Validation of Twitter screen names to check that the named Twitter
account for someone exists before letting you save that entry.
* Code that looks up and saves the Twitter user ID on adding and editing
a candidate.
* A `twitter_user_id` column to CSV output.
The management command (`candidates_update_twitter_usernames`) could reasonably be run once a day. It finds many Twitter screen names currently associated with …
> Store Twitter user IDs as well as screen names

- candidates/management/commands/candidates_update_twitter_usernames.py
The script was erroneously reporting that some Twitter accounts couldn't
be found because keys in the screen_name_to_user_id used the canonical
capitalization from Twitter, while the screen names in YNR's database
might use completely different case.
This commit fixes that by making sure that when storing or looking up
key / value paires in the screen_name_to_user_id dict, the key is
normalized to lower-case first.
> Normalize Twitter screen name case for use as dict keys

- cached_counts/templates/reports.html
- cached_counts/tests.py
- cached_counts/views.py
- candidates/templates/candidates/api.html
- candidates/templates/candidates/posts.html
- candidates/tests/test_group_elections.py
- candidates/tests/test_posts_view.py
- candidates/tests/uk_examples.py
- candidates/views/help.py
- candidates/views/posts.py
- elections/models.py
- elections/st_paul_municipal_2015/templates/candidates/posts.html
- elections/st_paul_municipal_2015/tests.py
- elections/uk/migrations/0003_adjust_roles_for_grouping.py
These commits change the following pages:
* `/numbers`
* `/posts`
* `/help/api`
... so that elections and posts are groups by:
* Group by `current=True`, then `current=False`
* Group by `for_post_role` (ordered alphabetically)
* Order election by election date (new to old) then election name
* Order posts by post label
When there are a lot of elections, this should make their structure
more obvious.  Grouping by `for_post_role` means that the elections
representing constituency and regional elections in the Scottish
Parliament Elections come together.
This also adds a link to the all candidates CSV file, which was
missing.
Fixes #863 
Fixes #598
> Group elections more logically on pages that list all elections / posts

- candidates/tests/test_search.py
- candidates/views/search.py
The search uses the text field in the index which is generated by
Haystack and escapes the content as it goes in. Search terms were not
being escaped which meant that names with an apostrophe in them never
matched.
This escapes search terms so they should not match the values in the
text field in the search index.
Fixes #862
> Fix searches featuring apostrophes

- alerts/migrations/0001_initial.py
- candidates/migrations/0008_membershipextra_organizationextra_personextra_postextra.py
- candidates/migrations/0015_add_configurable_extra_fields.py
- candidates/migrations/0019_add_yesno_to_extra_field_types.py
- candidates/migrations/0021_simplepopolofield.py
- elections/migrations/0001_initial.py
- moderation_queue/migrations/0001_initial.py
- moderation_queue/migrations/0004_queuedimage_why_allowed.py
- moderation_queue/migrations/0007_auto_20150303_1420.py
- moderation_queue/migrations/0008_add_ignore_to_decision_choices.py
- moderation_queue/migrations/0013_auto_20150916_1753.py
- official_documents/migrations/0001_initial.py
- official_documents/migrations/0002_officialdocument_document_type.py
- official_documents/migrations/0004_auto_20150410_1054.py
- official_documents/migrations/0005_auto_20150410_1307.py
- requirements.txt
``makemigrations`` fails in Python 3 if migrations contain both
bytes and Unicode strings.
Closes #847.
> Fix migrations for Python 3

- candidates/admin.py
- candidates/migrations/0030_update_complexfields_help_text.py
- candidates/migrations/0031_loggedaction_note.py
- candidates/models/db.py
- moderation_queue/tests/test_queue.py
- moderation_queue/views.py
This adds a note field to the LoggedActions model and uses that to store the rejection reason when uploaded photos are rejected during moderation.
It also adds a migration to update the help text of the complex fields because there was a mismatch there.
Fixes #896
> Log the rejection reason for photo moderation operations

- candidates/management/commands/candidates_update_twitter_usernames.py
The candidates_update_twitter_usernames script behaved less than ideally
in the case where none of their Twitter details correspond to a real
Twitter account (typically when they delete their account, or we only
have an old screen name that predates a change of screen name): it would
print out a warning, which would be emailed if the script is run from
a cron job.  This isn't ideal because we never want to be linking to
non-existent Twitter accounts from the site - the action you'd take on
seeing this warning is always going to be to remove or fix the bad data.
(The old values will still be in the version history, after all.)  You
might want to search for a new Twitter account too, but you can still do
that afterwards if the bad data were deleted.
This commit changes the behaviour of the …
> If none of the Twitter details are valid, remove them

- candidates/static/candidates/_people.scss
- candidates/templates/candidates/person-view.html
- candidates/templatetags/standing.py
- candidates/views/people.py
If a candidate has a party list position in an election this displays that alongside the candidacy in the Candidacies section of the person page.
Fixes #866
> Display the party list position on the person page

- candidates/static/candidates/_people.scss
- candidates/templates/candidates/person-view.html
- candidates/views/people.py
This adds a list of elections won to the top of the person page. There's no limit to how many it shows at the moment. It uses the styles from constituency page which are possibly a bit heavy for this. Possibly once #929 is done it could use that.
currently looks like:
> 856 show elections won on candidate page

- elections/migrations/0013_optional_election_area_type.py
- elections/models.py
Even though AreaType is a ManyToMany relationship and therefore option
unless blank=True is set on the field then the admin interface will
insist that you associate an election with an AreaType. We might not
want to do this if we are not using AreaType lookups, e.g. a simple YNR
instance which has no geolocation area lookup.
Fixes #942
> Allow election AreaType to be blank in forms/admin

- candidates/management/commands/candidates_create_areas_and_posts_from_mapit.py
The changes in this PR allow you to manually specify the MapIt area IDs instead of finding them from a MapIt query, clarify how the MAPIT-URL supplied is used, and allow all areas of a type to be found.
> Improvements to the command for creating posts / areas from MapIt 

- candidates/tests/auth.py
- candidates/tests/test_leaderboard.py
- candidates/tests/test_settings.py
- candidates/views/settings.py
No validation errors were being shown when trying to update settings at
/settings, because the form had the settings object instance set on it
in the wrong way: in get_context_data rather than via get_kwargs.
This commit fixes that, but this also exposed a bug where the cached
setting object was being updated when checking the validity of the
fields. This commit fixes that as well, otherwise the switch to
using get_form_kwargs causes test failures because of this bad
caching.
> Fix lack of validation errors from /settings and a caching bug

- candidates/forms.py
- candidates/models/popolo_extra.py
- candidates/static/candidates/_person_edit.scss
- candidates/templates/candidates/_person_form.html
- candidates/templates/candidates/person-edit-candidacy-pick-election.html
- candidates/templates/candidates/person-edit-candidacy-pick-party.html
- candidates/templates/candidates/person-edit-candidacy-pick-post.html
- candidates/templates/candidates/person-edit-candidacy-source.html
- candidates/templates/candidates/person-edit-candidacy-wizard.html
- candidates/tests/test_add_candidacy.py
- candidates/urls.py
- candidates/views/candidacies.py
- candidates/views/helpers.py
- candidates/views/people.py
- elections/models.py
- mysite/settings/conf.py
- requirements.txt
The motivation of this pull request is to deal with the problem that the person edit page included post and party selects for every current election in the database - this might be repeated for hundreds of elections, which makes the page very slow to load and crashes some browsers. (See https://github.com/mysociety/yournextrepresentative/pull/740 for more details.)
On the DemocracyClub fork of YNR, this problem has been dealt with by using Javascript to dynamically add those form elements. However, in this upstream versions, so far, all of the site works without Javascript, on the principle that progressive enhancement is a Good Thing, so I was reluctant to merge those changes as-is. This pull request adds a method which is not Javascript-dependent to do the same thing, and we can use …
> Add a wizard to add a new candidacy for a person

- candidates/forms.py
- candidates/templates/candidates/_person_form.html
- candidates/templates/candidates/person-edit-candidacy-pick-election.html
- candidates/tests/test_add_candidacy.py
- candidates/views/candidacies.py
- locale/en/LC_MESSAGES/django.po
Previously the default was to show all elections, whether they were
current or not, but @symroe pointed out that there might be thousands of
such elections, which in normal use would be irrelevant.
This commit makes the inclusion of non-current ('historic') elections in
the election picker stage an option - they're only shown if there's an
'historic=1' query parameter. There's also a link to that version of the
picker from the normal one.
> Add candidacy wizard: make historic elections an option

- candidates/templates/candidates/person-view.html
For example: https://candidates.democracyclub.org.uk/person/5544/mike-kane
There's a space between the year and closing bracket:
---
---
I've not tested this, but this looks like a likely fix, especially as pages with just a year don't have this problem and have `endblocktrans` with no line break.
> Remove space before closing bracket

- candidates/models/__init__.py
- candidates/models/popolo_extra.py
- candidates/models/sitesettings.py
- candidates/views/settings.py
- mysite/context_processors.py
There are two important situations where a SiteSettings object might not have been created:
* Setting up a site from scratch
* Running tests
In both those situations, migration `0032_sitesettings` in `candidates` is run before a site or a user exists, so the `SiteSettings` can't be created. This means that we need to take steps to make sure that the site still works when no SiteSettings object has been created.
> Fixes for SiteSettings objects not existing

- candidates/templates/candidates/_candidates_for_post.html
The name of the election is given once already for each list of candidates, leading to repetition and overly long title elements.
> KE: Remove name of election from list of candidates
