candidates/static/candidates/_footer.scss, candidates/static/candidates/style.scss, mysite/templates/base.html
Fixes #123.
Adds a large footer to the bottom of every page:
Lots of space to add more stuff or change the priorities or wording of what's already there.
=> Add footer with bylines and links to api and issue tracker

candidates/templates/candidates/about.html, candidates/templates/candidates/privacy.html, candidates/urls.py, mysite/templates/base.html
=> Add a privacy policy for YourNextMP

candidates/management/commands/candidates_update_incumbents_standing.py
=> A script to mark incumbents that we know nothing about as standing

candidates/static/candidates/_content.scss, candidates/static/candidates/_people.scss, candidates/static/candidates/_versions.scss, candidates/static/candidates/style.scss, candidates/static/js/versions.js, candidates/templates/candidates/person-versions.html, candidates/templates/candidates/person-view.html, candidates/templatetags/standing.py, candidates/update.py, mysite/templates/base.html
Fixes #146.
And partly addresses #138.
=> New profile page layout

candidates/csv_helpers.py, candidates/example-popit-data/persons-1953_embed=membership.organization.json, candidates/management/commands/candidates_create_csv.py, candidates/models.py, candidates/templates/candidates/api.html, candidates/tests/test_csv_export.py, candidates/urls.py, candidates/views.py, conf/crontab.ugly, conf/general.yml-example, media/.gitignore, mysite/context_processors.py, mysite/helpers.py, mysite/settings.py
Initial stab at #96.
The view is working fine, but I don't know the best way to save and serve the file (partly because I don't know about the deployment.
I expect it should use django's `Storage` class to write the file to the correct place, but advice from @mhl would be welcome.
=> CSV export

candidates/templates/candidates/about.html
This makes the following changes:
* Adds a disclaimer
* Adds mention of the Google Group
* Indicates that the photos and party logos are *not* CC-BY-SA licensed
=> Update the About page

candidates/static/candidates/_people.scss, candidates/templates/candidates/constituency.html, candidates/templates/candidates/person-view.html, candidates/templatetags/exists.py
Asks very clearly for missing email addresses.
=> "Add email" banners

candidates/templates/candidates/_person_in_list.html, candidates/templates/candidates/person-view.html
=> Use correct default image if `gender == "Female"`

cached_counts/tests.py, candidates/example-popit-data/search_incomplete_email_page=1.json, candidates/templates/candidates/finder.html, candidates/templates/candidates/person-edit.html, mysite/settings.py, mysite/urls.py, tasks/models.py, tasks/templates/tasks/field.html, tasks/templates/tasks/tasks_home.html, tasks/tests/test_views.py, tasks/urls.py, tasks/views.py
App for listing incomplete fields.
I wanted to do this in a new app to make things a big cleaner, and also we might add to it in future with more complex views.
Features:
* Pass the field name in to the URL.  This won't work in some cases where the data is only available in a 'deep field' in the returned data.  See `get_field` for some fixes to this
* Try to load a template called `field_[name].html` for the fields, reverting to `field.html`.  This is so we can add advise per field if we want to (like, not adding email addresses that aren't public, etc)
* We don't need to list many records per page, as we show the number at the top of the page.
Problems:
* Searches that search fields in the `versions` array might return incorrect data, as I can't find a way to search in `versions[0]` …
=> Incomplete field lists and tasks page

tasks/templates/tasks/field.html
As per @tfgg suggestion, add links to edit, search and twitter on missing fields list
=> Links to search and twitter on missing fields list

candidates/static/candidates/_parties.scss, candidates/templates/candidates/party.html
Thanks to @zarino for help with this.
=> Improve placement of logos on party pages on mobile

candidates/templates/candidates/constituency.html, candidates/views/constituencies.py
=> Add link to MeetYourNextMP on constituency pages

candidates/templates/candidates/person-view.html, candidates/tests/test_person_view.py, mysite/context_processors.py, mysite/settings.py
Also remove superfluous "</dd>" making HTML invalid.
=> Say "Contesting in 2015" before the election.

candidates/management/commands/candidates_create_csv.py, candidates/models.py, candidates/tests/test_csv_export.py, candidates/views/constituencies.py
Add ability to export 2010 version of CSV.
=> 2010 candidate csv

candidates/static/candidates/_versions.scss
=> Word wrap text in “versions” section

candidates/views/parties.py
=> Use party ID to select candidates on party page

candidates/management/commands/candidates_update_popit_parties_from_ec_data.py, candidates/templates/candidates/party.html, candidates/views/parties.py
The new Electoral Commission search tool has an API! (Albeit an undocumented one). Switching away from the current OpenElectoralCommission pipeline may even now help resolve some party-related issues.
=> Import from new EC API (rather than OEC)

README.md, Vagrantfile-example, conf/provision.sh
Adds a Vagrant file and a separate provision script and updates the README file.
Throws up a few depreciation and security warnings while it's installing packages, not sure if those are anything to worry about.
Closes #319
=> Add Vagrantfile and provision.sh

conf/crontab.ugly, moderation_queue/faces.py, moderation_queue/management/commands/moderation_queue_detect_faces_in_queued_images.py, moderation_queue/migrations/0010_auto_add_crop_bounds.py, moderation_queue/migrations/0011_queuedimage_face_detection_tried.py, moderation_queue/models.py, moderation_queue/static/moderation_queue/js/crop.js, moderation_queue/templates/moderation_queue/photo-review.html, moderation_queue/views.py, mysite/settings.py
This seems to work pretty well, but it's quite CPU intensive, so
the review page will take a couple of seconds to load; we may decide
that in practice this isn't worth it after all, but it seems to be
worth trying.
=> Photo review: use face detection from OpenCV to suggest a crop

moderation_queue/tests/test_queue.py
It seems that depending on the platform (or Pillow's supporting
libraries) the resulting image files won't be identical, so checking the
MD5sum isn't helpful.  Instead, it's probably fine to check that there's
an image file that's a PNG and of the right dimensions.
=> Instead of checking cropped image's MD5 hash, just check format and size

cached_counts/views.py, candidates/forms.py, candidates/views/areas.py, candidates/views/candidacies.py, candidates/views/constituencies.py, candidates/views/helpers.py, candidates/views/parties.py, candidates/views/people.py, elections/mixins.py, locale/en/LC_MESSAGES/django.po, official_documents/views.py
=> Add ElectionMixin for URLs using an election slug.

candidates/tests/test_flash_calls_to_action.py, candidates/views/people.py, elections/ar_elections_2015/templates/base.html, mysite/templates/generic_base.html
=> Add calls-to-action after adding / updating a person

elections/ar_elections_2015/static/candidates/style.scss
=> Remove underline on buttons on hover.

elections/ar_elections_2015/static/candidates/style.scss
=> Blue infoboxes, rather than dark green.

moderation_queue/views.py
=> Fix loss of alpha channel by converting cropped images to RGBA not RGB

candidates/management/commands/candidates_create_popit_posts.py, locale/cy_GB/LC_MESSAGES/django.po, locale/en/LC_MESSAGES/django.po, locale/es_AR/LC_MESSAGES/django.po
=> Make the format string for post labels localizable and overridable

candidates/static/candidates/_people.scss, candidates/static/candidates/style.scss, candidates/templates/candidates/_person_in_list.html, candidates/templates/candidates/ordered-party-list.html, elections/ar_elections_2015/static/candidates/style.scss, elections/bf_elections_2015/static/candidates/style.scss
=> Styling for party candidate positions

candidates/management/commands/.gitignore, candidates/management/commands/candidates_import_from_live_site.py
This assumes (and checks that you have) empty database tables before you
run the command.
To test this out you'll need to:
* switch country to `example` (because the other defined election apps
will try to create data when migrating them from scratch)
* drop the database you've defined for the example country
* create a new database of that name
* run `./manage.py migrate`
* run the command with, say:
./manage.py candidates_import_from_live_site https://edit.yournextmp.com/
=> Add a command to mirror a live YNR site from its API

elections/cr/management/commands/cr_create_basic_site.py
(This relies on `PartySet` objects already existing, so should be run after
`cr_import_parties_from_csv.py`.)
=> CR: add a script to create posts, elections, area types, etc.

mysite/settings/conf.py
It's common for people in Spanish-speaking countries to have
the 'es' language code first in their Accept-Language.  Indeed
Chrome seems not to offer 'es-cr' (Costa Rican Spanish) in its
language preferences at all.
This created a problem because we now have 'es-ar' (Argentinian Spanish)
and 'es-cr' in LANGUAGES; if you request 'es' then whichever was first
in LANGUAGES ('es-ar' with the current code) would always be used.  For
the Costa Rica site, it would make more sense to use 'es-cr' whenever
'es' is requested.
This commit achieves that by looking to see if LANGUAGE_CODE is present
in LANGUAGES, and, if so, moving that entry to the front.  LANGUAGE_CODE
should always be set to 'es-ar' for the Argentinian site and 'es-cr' for
the Costa Rican site, meaning we'll have the desired …
=> If Spanish ('es') is requested for CR or AR, use the site's default

candidates/templates/candidates/_person_update_call_to_action.html, candidates/templates/candidates/frontpage.html, elections/cr/templates/cr/frontpage.html, locale/cy_GB/LC_MESSAGES/django.po, locale/en/LC_MESSAGES/django.po, locale/en_US/LC_MESSAGES/django.po, locale/es_AR/LC_MESSAGES/django.po, locale/es_CR/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po
Mostly for the front page but also one untranslated string.
=> Small text tweaks for Costa Rica

candidates/models/versions.py, candidates/tests/test_revert.py, candidates/tests/test_update_view.py
The code has been in use for a few days with people being able to
add extra field values without them being recorded in the versions
array, so we should run:
./manage.py candidates_record_new_versions
Fixes #647
=> Record / restore extra field values in the versions field

candidates/forms.py, candidates/migrations/0019_add_yesno_to_extra_field_types.py, candidates/migrations/0020_cr_add_reelection_field.py, candidates/models/fields.py, candidates/templates/candidates/person-view.html, candidates/templatetags/extra_field_value.py, candidates/tests/test_extra_fields.py
This adds the ability to have extra fields associated with a person that have a dropdown with a Yes/No/Don't know option.
=> Add yes/no extra field

locale/cy_GB/LC_MESSAGES/django.po, locale/en/LC_MESSAGES/django.po, locale/en_US/LC_MESSAGES/django.po, locale/es_AR/LC_MESSAGES/django.po, locale/es_CR/LC_MESSAGES/django.po, locale/fr/LC_MESSAGES/django.po, mysite/templates/account/email/email_confirmation_message.txt, mysite/templates/account/email/email_confirmation_signup_message.txt, mysite/templates/account/email/email_confirmation_signup_subject.txt, mysite/templates/account/email/email_confirmation_subject.txt, mysite/templates/account/email/password_reset_key_message.txt, mysite/templates/account/email/password_reset_key_subject.txt
Copy across the allauth templates so the translations are handled by our .po files
=> Fix email translations

elections/cr/templates/cr/frontpage.html, elections/cr/tests.py, elections/cr/views.py, elections/models.py, elections/tests.py
Change the text on the CR frontpage post election.
Fixes #687
=> CR post election front page

candidates/diffs.py
The JSON for the diff stores the ID as it was at the time it was created.
This was causing 404 errors when `get_by_slug` was called on it
=> Catch case where older election IDs were causing a 404

candidates/migrations/0022_create_standard_simple_fields.py, candidates/static/candidates/_finder.scss, candidates/tests/test_merge_view.py, candidates/views/people.py, elections/uk/forms.py, elections/uk/management/commands/uk_create_regional_assembly_posts.py, elections/uk/migrations/0002_remove-gb-prefix.py, elections/uk/templates/base.html, elections/uk/templates/candidates/finder.html, elections/uk/templates/uk/constituency.html
Sorry that this isn't very neat, but these are some of the various updates I've made to the UK site that don't fall into any other PR.
=> Various UK updates

.travis.yml, alerts/admin.py, alerts/management/commands/alerts_send_alerts.py, alerts/migrations/0001_initial.py, alerts/models.py, alerts/templates/alerts/pretty_diff.txt, alerts/tests.py, alerts/views.py, candidates/tests/test_feeds.py, mysite/settings/conf.py, requirements.txt
This adds the ability to sign people up to email alerts when:
* A specific person is edited
* A person in an area is edited
* A person in a party is edited
The alerts can be sent either daily or hourly ( although if you are signed up to hourly alerts and daily alerts you will get the daily ones with the hourly ones )
It uses django-notifications to handle creating the notifications used for alerts, with a signal to create these attached to the save event of the LoggedAction model.
Alerts are created in the admin interface and require the django id of the object.
Fixes #606
=> Email alerts for person updates

candidates/templates/candidates/_candidates_for_post.html, candidates/templates/candidates/constituencies.html, candidates/templates/candidates/person-view.html, candidates/tests/test_areas_view.py, candidates/tests/test_person_view.py
=> Add links to all posts in the election from candidate lists and person pages

.gitignore
It would seem I remain the only Python 3 user. ;)
=> Add Python 3 cache folder to .gitignore

elections/example/static/candidates/style.scss
It wouldn't compile without the mixins.
=> Update example candidate CSS for @9122a8d

mysite/templates/generic_base.html
``LANGUAGE_CODE`` is the active locale.
=> Replace hardcoded 'lang' in generic_base with ``LANGUAGE_CODE``

candidates/forms.py
This introduces a new class, ``StrippedCharField``, which
inherits from ``CharField`` and backports its Django 1.9 ``strip``
argument (see django/django@11cac1b).  It replaces all uses
of ``CharField`` in candidate forms with ``StrippedCharField``.
Closes #333.
=> Strip leading and trailing whitespace in submitted candidate data

.travis.yml, bin/pre-deploy, mysite/settings/conf.py, requirements.txt
This provides a massive performance boost for dev environments
(I'm making a pull request from this commit of Sym's: we need to test
whether libsass and this django-pipeline upgrade work properly on
mySociety's servers, but I love this change and I'm keen to merge it -
development is *so* much nicer.)
Fixes #707
=> Move to libsass and pipeline 1.6.8

candidates/tests/test_ordered_party_list.py, candidates/views/constituencies.py
=> fix party pre-selection in new candidate party list page form

candidates/templates/candidates/ordered-party-list.html, candidates/views/constituencies.py
=> Replace old candidate form in party list with newer sectioned one

candidates/static/js/constituency.js, candidates/templates/candidates/_candidates_for_post.html
Ask if people want to unset the winners and include count of how many
will be unset to make sure they understand it's all winners
Fixes #935
=> Add confirmation dialog for unselecting winners

elections/uk/management/commands/uk_import_2010_winners.py
This fetches the list of MPs at the 2010 general election from
TheyWorkForYou and uses the parlparse ID to find the corresponding YNR
people and set the candidate property on the 2010 candidate membership.
Fixes #931
=> script to set winners from 2010 UK general election

candidates/migrations/0035_migrate_in_settings_comments.py, candidates/models/sitesettings.py, candidates/templates/candidates/settings.html, conf/general.yml-example, mysite/context_processors.py, mysite/templates/generic_base.html
This addresses my comments [here](https://github.com/mysociety/yournextrepresentative/issues/943#issuecomment-226461018).
=> Polish settings
